# Generated by Django 6.0.3 on 2026-03-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_appointment_assigned_staff_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='commission_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='service',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
